name: CI
on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERYAPIKEY }}
          BUILDVER: ${{ github.ref }}
        shell: pwsh
        run: |
          echo $env:BUILDVER
          ./build_scripts/build.ps1
          # Publish-Module -path ./PowerAMT -NuGetApiKey $env:NUGET_KEY -ProjectUri 'https://github.com/netricsag/PowerAMT' -Tags "intel","AMT","OpenAMT","Open amt","OACT" -Verbose
