name: CI
on:
  push:
    branches: [main]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERYAPIKEY }}
          BUILDVER: "1.0.0"
        shell: pwsh
        run: |
          ./build_scripts/build.ps1
          Publish-Module -path ./PowerAMT -NuGetApiKey $env:NUGET_KEY -Verbose
