name: CI
on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERYAPIKEY }}
          BUILDVER: ${{ env.RELEASE_VERSION }}
        shell: pwsh
        run: |
          ./build_scripts/build.ps1
          Publish-Module -path ./PowerAMT -NuGetApiKey $env:NUGET_KEY -ProjectUri 'https://github.com/netricsag/PowerAMT' -Tags "intel","AMT","OpenAMT","Open amt","OACT" -Verbose
